[package]
name = "tethermanager"
version = "0.1.0"
authors = ["cmatri <cperkin4@gmu.edu>"]
edition = "2018"

[dependencies]
libusb = "0.3.0"
notify-rust = "3.6.0"
psutil = "1.5.0"
simple-error = "0.2.1"
signal-hook = "0.1.9"
crossbeam-channel = "0.3.8"
